' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Controller-Klasse

interface Promise<T>
interface Readonly<T>

package @nestjs/graphql {
  annotation Resolver
  annotation UseInterceptors
  annotation Query
  annotation Args

  Resolver .left[hidden].> Promise
}

package generated.prisma {
  class Prisma
  class FilmGetPayload<T>
  Prisma +-- FilmGetPayload
}

package film {
  package service {
    class FilmService << control >>
  }

  package graphql #DDDDDD {
    class "type FilmDTO = Omit<Film, 'schauspieler' | 'aktualisiert' | 'erzeugt'" as FilmDTO
    hide FilmDTO circle

    interface IdInput {
        id: number
    }

    class FilmQueryResolver << control >> << @Resolver() >> << @UseInterceptors() >> {
      + @Query() async film(@Args() id: IdInput): Promise<Readonly<FilmGetPayload>>
      + @Query() async filme(@Args() beschreibung: string | undefined): Promise<FilmDTO[]>
    }

    FilmQueryResolver o-down-> "1" FilmService : service
    FilmQueryResolver ..> FilmDTO
    FilmQueryResolver ..> IdInput
    FilmQueryResolver .up.> Resolver

    FilmQueryResolver .up.> Promise
    FilmQueryResolver .up.> Readonly

    FilmQueryResolver .up.> FilmGetPayload

    IdInput .down[hidden].> FilmService
    FilmService .down[hidden].> Prisma
    FilmService .down[hidden].> FilmGetPayload
  }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
